version: '3.8'

services:
  mcp_server:
    build: ./mcp_server
    ports:
      - "8000:8000"
    restart: always

  mcp_client_gradio:
    build: ./mcp_client_gradio
    ports:
      - "7860:7860"
    depends_on:
      - ollama
    restart: always

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    runtime: nvidia # Activ GPU
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility